public enum RequestType {
    CERTIFICATE,
    SCHEDULE_CHANGE,
    ACADEMIC_ISSUE,
    ACADEMIC_APPEAL,
    DISCIPLINARY_CASE,
    NEW_SUBJECT,
    NEW_PROGRAM,
    ACADEMIC_AGREEMENTS,
    INSTITUTIONAL_POLICY,
    MERGER
}
